/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;

import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author yaniyan
 */
public class info extends javax.swing.JFrame {

    /**
     * Creates new form info
     */
  public info() {
        initComponents();

        // === Komponen utama ===
        JTextArea txtInfo = new JTextArea();
        txtInfo.setEditable(false);
        txtInfo.setLineWrap(true);
        txtInfo.setWrapStyleWord(true);

        JScrollPane scroll = new JScrollPane(txtInfo);
        scroll.setBounds(10, 10, 475, 475);
        add(scroll);

        JButton btnIndo = new JButton("Bahasa Indonesia");
        JButton btnEnglish = new JButton("English");
        btnIndo.setBounds(10, 500, 200, 30);
        btnEnglish.setBounds(250, 500, 200, 30);
        add(btnIndo);
        add(btnEnglish);

        // === Teks awal default (Indonesia) ===
        txtInfo.setText(getTextIndonesia());

        // === Event tombol ubah bahasa ===
        btnIndo.addActionListener(e -> txtInfo.setText(getTextIndonesia()));
        btnEnglish.addActionListener(e -> txtInfo.setText(getTextEnglish()));

        // === Pengaturan dasar JFrame ===
        setLayout(null);
        setSize(510, 580);
        setTitle("Info Aplikasi Kasir");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

private String getTextIndonesia() {
    return """
Simple aplikasi kasir restoran
Dibuat oleh: Dani Junianto 12 Rpl - 08
                        
Penjelasan alur:
- Login
  Login menggunakan Username dan Password.
                     
- Kelola Menu
  User melakukan pembelian bahan-bahan untuk menambah stok bahan.
  Setelah stok tersedia, user dapat membuat menu.
  Setiap menu memiliki resep yang terdiri dari beberapa bahan yang digunakan.
  Saat menu dibuat atau dijual, sistem otomatis mengurangi stok bahan sesuai resep.
Contoh:
  Pembelian: Nasi 10 kg
  Resep menu: Nasi Goreng menggunakan Nasi 0.25 kg per porsi
  Setiap kali 1 porsi Nasi Goreng dibuat, stok Nasi akan berkurang 0.25 kg.
                     
- Fitur Transaksi
  Setiap transaksi penjualan akan mengurangi stok menu sesuai dengan jumlah yang dipesan.
  Misalnya, jika stok Nasi Goreng tersisa 10 porsi dan pelanggan memesan 3 porsi,
  maka setelah transaksi, stok Nasi Goreng menjadi 7 porsi.
                                   
Fitur:
- Kasir Transaksi Penjualan
- Pembelian Bahan-Bahan
- Laporan Transaksi
- Panel Admin
- Kelola User
- Kelola Menu
- Kelola Bahan
- Kelola Resep
                        
Terima kasih telah menggunakan aplikasi ini!
""";
}

private String getTextEnglish() {
    return """
Simple restaurant cashier application
Created by: Dani Junianto 12 Rpl - 08
                        
Flow explanation:
- Login
  Login using Username and Password.
                     
- Manage Menu
  The user purchases ingredients to add stock.
  Once stock is available, the user can create menu items.
  Each menu item has a recipe consisting of several ingredients.
  When a menu is made or sold, the system automatically reduces ingredient stock according to the recipe.
Example:
  Purchase: Rice 10 kg
  Menu recipe: Fried Rice uses 0.25 kg of rice per portion.
  Every time 1 portion of Fried Rice is made, rice stock decreases by 0.25 kg.
                     
- Transaction Feature
  Each sales transaction reduces menu stock based on the number ordered.
  For example, if Fried Rice stock is 10 portions and a customer orders 3,
  then after the transaction, the stock becomes 7 portions.
                                   
Features:
- Cashier Sales Transaction
- Ingredient Purchases
- Transaction Reports
- Admin Panel
- Manage Users
- Manage Menu
- Manage Ingredients
- Manage Recipes
                        
Thank you for using this application!
""";
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
