/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;

import java.awt.Color;
import java.awt.Component;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;
import java.sql.SQLException;

/**
 *
 * @author user
 */
public class menu extends javax.swing.JFrame {
// Di form menu
menuKasir kasirForm;
admin adminForm;
public menu(admin adminForm) {
    initComponents();
    this.adminForm = adminForm;
        tampil_data();
        aturTampilanTabel();
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // <-- PENTING

}
public menu(menuKasir kasirForm) {
    initComponents();
    this.kasirForm = kasirForm;
        tampil_data();
        aturTampilanTabel();
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // <-- PENTING

}
public menu() {
    initComponents();
                    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // <-- PENTING

}

private void aturTampilanTabel() {
    tableMenu.setRowHeight(30);

}

public void tampil_data(){
   DefaultTableModel tabel = new DefaultTableModel();
     tabel.addColumn("idMenu");
     tabel.addColumn("namaMenu");
     tabel.addColumn("hargaMenu");
     tabel.addColumn("stokMenu");
     tabel.addColumn("kategori");

//    tabel.addColumn("harga_barang");
//   tabel.addColumn("stok_barang");

   try{
   Connection conn = (Connection)kasir.koneksi.dbKonek();
   String sql = "select*from menu";
   PreparedStatement pst = conn.prepareStatement(sql);
   ResultSet rs = pst.executeQuery();
   
   while (rs.next()){
       tabel.addRow(new Object[]{
       rs.getString(1),
       rs.getString(2),
       rs.getString(3),
       rs.getString(4),
       rs.getString(5)});
       
   }
   tableMenu.setModel(tabel);
   // Custom cell renderer untuk warnai stok
// Custom cell renderer untuk kolom stok
tableMenu.getColumnModel().getColumn(3).setCellRenderer(new DefaultTableCellRenderer() {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
                                                   boolean isSelected, boolean hasFocus,
                                                   int row, int column) {
        Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

        try {
            int stok = Integer.parseInt(value.toString());
            if (stok < 5) {
                c.setBackground(Color.RED);   // background merah
                c.setForeground(Color.WHITE); // teks putih biar kontras
            } else {
                // reset warna normal kalau stok aman
                if (isSelected) {
                    c.setBackground(table.getSelectionBackground());
                    c.setForeground(table.getSelectionForeground());
                } else {
                    c.setBackground(Color.WHITE);
                    c.setForeground(Color.BLACK);
                }
            }
        } catch (Exception e) {
            c.setBackground(Color.WHITE);
            c.setForeground(Color.BLACK);
        }

        return c;
    }
});


   }catch(Exception e){
               e.printStackTrace(); 

   }

   
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMenu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMenu.setRowHeight(30);
        tableMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMenuMouseClicked
    }//GEN-LAST:event_tableMenuMouseClicked
private void kurangiStok(String idmenu) {
    try {
          String sql = "UPDATE menu SET stok = stok - 1 WHERE idmenu = ?";
             Connection conn = (Connection)kasir.koneksi.dbKonek();

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, Integer.parseInt(idmenu)); // casting ke integer
        pst.executeUpdate();
        pst.close();
        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal mengurangi stok: " + e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMenu;
    // End of variables declaration//GEN-END:variables
}
